//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTable
    {
        public int gradeId { get; set; }
        public Nullable<int> studentId { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<short> exam1 { get; set; }
        public Nullable<short> exam2 { get; set; }
        public Nullable<short> exam3 { get; set; }
        public Nullable<decimal> avarage { get; set; }
        public Nullable<bool> situation { get; set; }
    
        public virtual CoursesTable CoursesTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
